//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Icl")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://127.0.0.1:11223", ConfigurationName="ServiceReference1.ServiceA")]
    public interface ServiceA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1:11223/ServiceA/GetDataA", ReplyAction="http://127.0.0.1:11223/ServiceA/GetDataAResponse")]
        string GetDataA(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1:11223/ServiceA/GetDataA", ReplyAction="http://127.0.0.1:11223/ServiceA/GetDataAResponse")]
        System.Threading.Tasks.Task<string> GetDataAAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1:11223/ServiceA/GetDataUsingDataContractA", ReplyAction="http://127.0.0.1:11223/ServiceA/GetDataUsingDataContractAResponse")]
        TestWCF.ServiceReference1.CompositeType GetDataUsingDataContractA(TestWCF.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://127.0.0.1:11223/ServiceA/GetDataUsingDataContractA", ReplyAction="http://127.0.0.1:11223/ServiceA/GetDataUsingDataContractAResponse")]
        System.Threading.Tasks.Task<TestWCF.ServiceReference1.CompositeType> GetDataUsingDataContractAAsync(TestWCF.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAChannel : TestWCF.ServiceReference1.ServiceA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAClient : System.ServiceModel.ClientBase<TestWCF.ServiceReference1.ServiceA>, TestWCF.ServiceReference1.ServiceA {
        
        public ServiceAClient() {
        }
        
        public ServiceAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDataA(int value) {
            return base.Channel.GetDataA(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAAsync(int value) {
            return base.Channel.GetDataAAsync(value);
        }
        
        public TestWCF.ServiceReference1.CompositeType GetDataUsingDataContractA(TestWCF.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractA(composite);
        }
        
        public System.Threading.Tasks.Task<TestWCF.ServiceReference1.CompositeType> GetDataUsingDataContractAAsync(TestWCF.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAAsync(composite);
        }
    }
}
