//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWCF.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://127.0.0.1:11225", ConfigurationName="ServiceReference3.ServiceC")]
    public interface ServiceC {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://127.0.0.1:11225/ServiceC/SetDataC")]
        void SetDataC(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://127.0.0.1:11225/ServiceC/SetDataC")]
        System.Threading.Tasks.Task SetDataCAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCChannel : TestWCF.ServiceReference3.ServiceC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCClient : System.ServiceModel.ClientBase<TestWCF.ServiceReference3.ServiceC>, TestWCF.ServiceReference3.ServiceC {
        
        public ServiceCClient() {
        }
        
        public ServiceCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetDataC(int value) {
            base.Channel.SetDataC(value);
        }
        
        public System.Threading.Tasks.Task SetDataCAsync(int value) {
            return base.Channel.SetDataCAsync(value);
        }
    }
}
